version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    build:
      context: ./producer
    container_name: kafka_producer
    depends_on:
      - kafka
    volumes:
      - ./data:/data

  pyspark:
    build:
      context: ./pyspark
    container_name: pyspark_streaming
    depends_on:
      - kafka
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MODE=master
    links:
      - kafka
    volumes:
      - ./pyspark:/app
    ports:
      - "8000:8000" # Original JMX port
      - "7000:7000" # Add this for the Python Prometheus client

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus web UI
    volumes:
      - ./prometheus/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: 'grafana/grafana:latest'
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"

volumes:
  influxdb-data:
    driver: local
  grafana-storage:
    driver: local



